### PR TITLE
Don't set any project path by default

### LINKED ISSUE #123: Pre commit/push hooks fail in the latest version
Hi 👋 ,

Thanks for this project!

Pre-commit or push hooks fail in the latest version for me under macOS Monterey 12.3 (whether it matters), I wonder if conditional `cd` shown in the screenshot is the culprit. (this [commit](https://github.com/qgadrian/elixir_git_hooks/commit/d5c962298aa048269d85e92589e692e6dde29d41))

image

image

My config:

```elixir
if Mix.env() == :dev do
  config :git_hooks,
    verbose: true,
    hooks: [
      pre_commit: [
        tasks: [
          {:cmd, "mix format --check-formatted"}
        ]
      ],
      pre_push: [
        tasks: [
          {:cmd, "mix quality"}
        ]
      ]
    ]
end
```

Seem to work fine with the version 0.6.5.

How to reproduce:
1. Download [git_hooks_bug.zip](https://github.com/qgadrian/elixir_git_hooks/files/8598525/git_hooks_bug.zip)
2. `mix deps.get && mix compile`
3. `touch test.txt && git commit -m whatever`

### PR DESCRIPTION
**Pull request by qgadrian**
This PR removes the auto directory change on the project. To change the path where to execute the hooks, a `project_path` config will need to be set.

The changes here can potentially break a current setup for a project that is relying on the _auto cd_.

Fixes #123 #133 #191

### CODE REVIEW

**Comment by djthread** [comment]
Thanks for looking at this, Adrián! I just gave this another try and noticed the same thing as I mentioned on #123. Checking out my project freshly and setting the git_hooks dep in mix.exs with 'github' and 'branch' set to this PR, 'mix compile' shows the installing message, but at the end, my `pre-push` file is not created under `.git/hooks`.

```
↗ Installing git hooks...
```

I even looked at your diff here and tried swapping back the line in `lib/mix/tasks/git_hooks/install.ex` which seemed to be the only relevant change... Same result every time I `rm -rf _build/dev/lib/git_hooks` and `mix compile`: no hook file generated!

However, if I then switch back to `0.7.3` and do `mix deps.get`, `mix compile`, of course the installing message appears here, too... but the git hook file is created as expected, consistently!

I can't seem to even theorize what would make the difference! ...

**Comment by qgadrian** [comment]
> Thanks for looking at this, Adrián! I just gave this another try and noticed the same thing as I mentioned on #123. Checking out my project freshly and setting the git_hooks dep in mix.exs with 'github' and 'branch' set to this PR, 'mix compile' shows the installing message, but at the end, my `pre-push` file is not created under `.git/hooks`.
> 
> ```
> ↗ Installing git hooks...
> ```
> 
> I even looked at your diff here and tried swapping back the line in `lib/mix/tasks/git_hooks/install.ex` which seemed to be the only relevant change... Same result every time I `rm -rf _build/dev/lib/git_hooks` and `mix compile`: no hook file generated!
> 
> However, if I then switch back to `0.7.3` and do `mix deps.get`, `mix compile`, of course the installing message appears here, too... but the git hook file is created as expected, consistently!
> 
> I can't seem to even theorize what would make the difference! ...

That is weird, @djthread can you please add the `config :git_hooks, verbose: true` config and try again? What is the path used to install the hooks? 

I've just tried on a fresh install and it worked fine. Just to be clear, the hooks install will only occur when the dep is compiled or when you execute `mix git_hooks.install`, but that doesn't seem to be your case :/

**Comment by MajdSehwail** [comment]
Hi @qgadrian 

Thanks for working on this fix. I've pulled this PR and the auto installation is working as expected when specifying the project's root 👍 

``` config :git_hooks, auto_install: true, verbose: true, project_path: File.cwd!()```

Would really appreciate if included in the next version release, cheers!

**Comment by qgadrian** [comment]
> Hi @qgadrian
> 
> Thanks for working on this fix. I've pulled this PR and the auto installation is working as expected when specifying the project's root 👍
> 
> ` config :git_hooks, auto_install: true, verbose: true, project_path: File.cwd!()`
> 
> Would really appreciate if included in the next version release, cheers!

Thanks for the feedback. Do you need to explicitly specify the `:project_path` field?

IMO this dependency should work out of the box with _default project architecture, and use that option only for edge cases. That means, without setting `:project_path` it should work on any _mix new project_.

**Comment by MajdSehwail** [comment]
> IMO this dependency should work out of the box with _default project architecture, and use that option only for edge cases. That means, without setting `:project_path` it should work on any _mix new project_.

Yes we had to specifically set it. Perhaps it's due to having multiple config files (`git_hooks` config only exists in `dev.exs`)?
```
.
├── mix.exs
├── mix.lock
├── config
   ├──config.exs
   ├──dev.exs
   ├──prod.exs
   ├──releases.exs
   ├──test.exs
├── apps
├── deploy
├── rel
├── .github
├── .credo.exs
├── .formatter.exs
├── .tools-versions
├── LICENSE
└── README.md
```

**Comment by sergiolc** [comment]
Hi @qgadrian,

the problem seems to be here:
```
  def resolve_app_path do
    repo_path =
      resolve_git_path_based_on_git_version()
      |> Path.dirname()

    Path.relative_to(File.cwd!(), repo_path)
  end
```

During auto install, `File.cwd!()` returns `/<project>/deps/git_hooks` and `repo_path` returns `../../.git/`.

I couldn't figure out what's the purpose of `Path.relative_to(File.cwd!(), repo_path)` here.

When running `mix git_hooks.install`, `File.cwd!()` returns `/<project>` and `repo_path` returns `.git/`, so the `repo_path` is not doing anything.

Can you double check this and provide some details please.

Thanks

**Comment by qgadrian** [comment]
I know it’s been a while since this issue was first reported, but I believe I’ve finally got it covered 🤞 

#### Technical Solution

The main challenge was path resolution inconsistencies when running the hook installation from within the deps directory (deps/git_hooks). 

To address this, I updated the path resolution logic in `GitHooks.Git.GitPath.resolve_app_path/0`. The updated implementation now traverses up the directory tree to locate the `.git` folder, ensuring that the correct project root is identified even when the working directory is within a nested dependency.

#### New Pre-Release for Testing

Although I added some extra tests to validate this new approach, and to make it easier for everyone to verify these changes, I’ve published a new pre-release `v0.8.0.pre1` version. 

I will be great if someone can test it out in a _real project_ and let me know if there are any issues or edge cases that need attention.

**Comment by qgadrian** [comment]
Released in https://github.com/qgadrian/elixir_git_hooks/releases/tag/v0.8.0

**Pull request merged**
