### PR TITLE
Use git to find .git or fall back to old behavior

### PR DESCRIPTION
**Pull request by mjc**
This should fix finding git directories that are above the current directory, as well as deal with nonstandard git folders, etc.

Improvements needed to merge this PR:
- [x] call out to git
- [x] validate git_path config option
- [x] update hook to run mix in the project root
- [x] test git path detection
- [x] test legacy path generation 

Algorithm:

    Try app env

    if :detect or empty, go to detection
    if exists, return path
    if error, error or warn and raise

    Detection

    If File.cwd!() does not work, give up
    If parent path is deps, go up one level
    If git exists, use its output without verification
    If git does not exist, use fallback
    If fallback is not right, use submodule

This greatly reduces the chance of failure when git would just do the right thing. The `git_path` config is not enough for a lot of cases, like when providing an absolute path is not feasible and different people have their git checkouts configured differently.

### CODE REVIEW

**Comment by qgadrian** [comment]
Hey @mjc, thanks for the contribution.

I believe this would fix #96 correct?

Feel free to open another PR with a refactor proposal btw 🙌

**Comment by mjc** [comment]
Yes it should absolutely fix #96.

I need to revise this to work correctly if git does not exist in your path, so give me a minute before you merge this.

I'll happily also open a new PR for the refactor.

**Comment by qgadrian** [comment]
> Yes it should absolutely fix #96.
> 
> I need to revise this to work correctly if git does not exist in your path, so give me a minute before you merge this.
> 
> I'll happily also open a new PR for the refactor.

Sure.

I've been trying to setup a test scenario on Github actions to test the issue, but I'm still struggling with it

**Comment by mjc** [comment]
So on further investigation I think the algorithm needs to look like this:

1. detect if we are using a git or path version of this hex package and go up to the parent (`deps`) folder to do our detection
2. detect if we have the `git` command and try that
3. fall back to existing detection methods, maybe modifying them to start in deps folder.

Does that sound right? I will try and test it some, I've got 7 different configurations like this.

A github action for this would probably look like:
1. Outside of the package checkout, make several directory trees with `.git` in increasingly further up locations
2. copy the package into the deps folder of each of these
3. compile and check for the hooks
4. remove hooks and .git folder from the package in each of those
5. re-run

I'm not sure I can find paid time to make the github action, unfortunately.

**Comment by mjc** [comment]
Alternately, we could gather all the paths in preferred order, remove ones that are not dirs, and pick the first one?  Depends how hard you want to try to do the right thing

**Comment by mjc** [comment]
I hate to do the refactor I was after in this PR but it was
1. really not easy enough to graft this behavior on
2. in need of more tests

Tests are in progress.

Algorithm I ended up using:

1. Try app env

  - if `:detect` or empty, go to detection
  - if exists, return path
  - if error, error or warn and raise

2. Detection

  - If parent path is deps, go up one level
  - If git exists, use its output
  - If git does not exist, use fallback
  - If fallback is not right, use submodule

**Comment by mjc** [comment]
Unanswered question: When should we raise vs just logging and continuing?

**Comment by qgadrian** [comment]
This issue got a simpler solution by just using git client directly (https://github.com/qgadrian/elixir_git_hooks/commit/49ca50e56f4ada2d5ad4d7198cc2bfef2681894d)

I think the interesting part in this PR is the submodule project and the tests. @mjc it would be awesome if you can rebase this PR so we can benefit from adding the test suit you created, otherwise I will create an issue to add them.

**Comment by mjc** [comment]
> This issue got a simpler solution by just using git client directly ([49ca50e](https://github.com/qgadrian/elixir_git_hooks/commit/49ca50e56f4ada2d5ad4d7198cc2bfef2681894d))

This PR is also using rev-parse. I was aiming for the least changes to the way the existing code works. I can try to get to it this week, but no guarantees.

**Comment by qgadrian** [comment]
I'm closing this issue since this project no longer will support all edge cases and different scenarios for project/git/deps architecture. 

Instead of that, I will add configs to allow any project to decide where things are placed so we can keep this project agnostic of the projects using it.

**Pull request closed without merging**
