### PR TITLE
Configurability to run hooks only on a certain branch

### LINKED ISSUE #84: Configurability to run hooks only on a certain branch

### PR DESCRIPTION
**Pull request by paulo-silva**
### Updated

Closes #84

This PR adds the option to run hooks only on a certain branch by adding a new global and git hook type config called `branches`, that can be configured like below:

```elixir
config :git_hooks, branches: [whitelist: ["master", "main", "featprefix-.*"], blacklist: ["wip-.*"]]
```

or

```elixir
config :git_hooks,
  hooks: [
    pre_commit: [
      branches: [whitelist: ["master", "main", "featprefix-.*"], blacklist: ["wip-.*"]
    ]
  ]
```

You can set only whitelist or blacklist as well:

```elixir
config :git_hooks,
  hooks: [
    pre_commit: [
      branches: [blacklist: ["wip-.*"]]
    ]
  ]
```

Also, this option is completely optional, so if it is not provided, all the branches will be able to execute git_hooks commands.

### CODE REVIEW

**Comment by qgadrian** [comment]
Hey @paulo-silva, thanks for the contribution! 🤘

I was thinking of using a list of regular expressions to make this feature even more flexible, otherwise, this won't escalate in some cases.

A use case would be supporting something like:

```elixir
config :git_hooks, branches: [whitelist: ["master", "main", "featprefix-.*"], blacklist: ["wip-.*"]]
```

Can you update the PR to support it?

**Comment by paulo-silva** [comment]
> Hey @paulo-silva, thanks for the contribution! 🤘
> 
> 
> 
> I was thinking of using a list of regular expressions to make this feature even more flexible, otherwise, this won't escalate in some cases.
> 
> 
> 
> A use case would be supporting something like:
> 
> 
> 
> ```elixir
> 
> config :git_hooks, branches: [whitelist: ["master", "main", "featprefix-.*"], blacklist: ["wip-.*"]]
> 
> ```
> 
> 
> 
> Can you update the PR to support it?

Hey @qgadrian, thank you for the reply! Yep, will do!

**Comment by paulo-silva** [comment]
Hey @qgadrian, I've added the proposed changes, would you mind taking another look when you can? Thanks in advance 🙇

**Comment by qgadrian** [comment]
Perfect, thanks @paulo-silva!

**Pull request merged**
