### PR TITLE
Added support for env vars

### PR DESCRIPTION
**Pull request by akoutmos**
This allows tasks to have environment variables passed to them so you can do things like the following and ensure that the proper items are in place before running tests:

```elixir
tasks: [
  {:cmd, "mix ecto.setup", env: [{"MIX_ENV", "test"}]},
  "mix test"
]
```

If no args are passed, and empty list is provided to `System.cmd/3`

### CODE REVIEW

**Comment by akoutmos** [comment]
Friendly bump :)

**Comment by qgadrian** [comment]
Hey @akoutmos sorry I didn't have to take a look at this, I want to get ride of the `TODO` in the code instead of allowing it on credo.

I will merge it ASAP, thanks for the contribution! 🎉

**Comment by akoutmos** [comment]
Thanks for getting back to me! Are you talking about this one? https://github.com/qgadrian/elixir_git_hooks/blob/master/lib/mix/tasks/git_hooks/run.ex#L77

**Comment by akoutmos** [comment]
Want me to remove the TODO in this PR?

**Comment by qgadrian** [comment]
@akoutmos, please do. I updated master branch with the deprecation so no more TODOs pending anymore

**Comment by akoutmos** [comment]
Reverted the credo change. Let me know if there is anything else you would like me to do :)

**Comment by qgadrian** [comment]
Thanks for the contribution @akoutmos 🎉

**Comment by akoutmos** [comment]
No problem :). Thanks for the awesome lib!!

**Pull request merged**
